name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Optional: Run workflow manually
  workflow_dispatch:
  # Optional: Run workflow when pushing on master/main
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write

    steps:
      - name: Generate Full-year Calendar Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: 'commit'
          filename: metrics.plugin.isocalendar.fullyear.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Generate Full History Calendar Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: 'commit'
          filename: metrics.plugin.calendar.full.svg
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

      - name: Generate Succinct Report with PWA Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://lecoq.io
          plugin_pagespeed_pwa: yes

      - name: Commit Metrics
        if: ${{ steps.generate-full-year-calendar-metrics.outputs.output_action == 'commit' || steps.generate-full-history-calendar-metrics.outputs.output_action == 'commit' || steps.generate-succinct-report-with-pwa-metrics.outputs.output_action == 'commit' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: 'metrics'
          message: 'Update metrics'
          author_name: 'github-actions'
          author_email: 'actions@github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
