name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Optional: Run workflow manually
  workflow_dispatch:
  # Optional: Run workflow when pushing on master/main
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write

    steps:
      - name: Generate Full-year Calendar Metrics
        id: generate-full-year-calendar-metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: 'commit'
          filename: metrics.plugin.isocalendar.fullyear.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Generate Full History Calendar Metrics
        id: generate-full-history-calendar-metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: 'commit'
          filename: metrics.plugin.calendar.full.svg
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

  

     

      - name: Generate Pinned Repositories Metrics
        id: generate-pinned-repositories-metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.repositories.pinned.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 5

      - name: Generate Recently Used Languages Metrics
        id: generate-recently-used-languages-metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: 'commit'
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14

      - name: Generate Repositories and Diff History Metrics
        id: generate-repositories-and-diff-history-metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.lines.history.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1
          repositories_skipped: |
            @use.patterns
            */*
            +lowlighter/metrics

      - name: Generate Featured Star List Metrics
        id: generate-featured-star-list-metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 2
          plugin_starlists_only: TC39

      - name: Generate Featured Star List Languages Metrics
        id: generate-featured-star-list-languages-metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.languages.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Awesome

      - name: Commit Metrics
        if: |
          steps.generate-full-year-calendar-metrics.outputs.output_action == 'commit' ||
          steps.generate-full-history-calendar-metrics.outputs.output_action == 'commit' ||
          steps.generate-pinned-repositories-metrics.outputs.output_action == 'commit' ||
          steps.generate-recently-used-languages-metrics.outputs.output_action == 'commit' ||
          steps.generate-repositories-and-diff-history-metrics.outputs.output_action == 'commit' ||
          steps.generate-featured-star-list-metrics.outputs.output_action == 'commit' ||
          steps.generate-featured-star-list-languages-metrics.outputs.output_action == 'commit'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'metrics'
          message: 'Update metrics'
          author_name: 'github-actions'
          author_email: 'actions@github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
